
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class Simbolos {
  /* terminals */
  public static final int WORD = 3;
  public static final int error = 1;
  public static final int NUMBER = 4;
  public static final int COD_POSTAL = 2;
  public static final int EOF = 0;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "COD_POSTAL",
  "WORD",
  "NUMBER"
  };
}

